name: Monthly Data Refresh

on:
  schedule:
    - cron: '0 0 1 * *'  # Run at 00:00 on the 1st day of each month
  workflow_dispatch:      # Also allow manual trigger from GitHub UI

jobs:
  update-cleaned-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run cleaning script
        run: python scripts/clean_data.py

      - name: Commit cleaned data
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add data/cleaned_data.csv
          git commit -m "Auto-update cleaned data (monthly)" || echo "No changes to commit"
          git push

