name: Monthly Data Refresh

on:
  push:
    paths:
      - 'data/raw_data.xlsx'         # Trigger when raw data file changes
  schedule:
    - cron: '0 0 1 * *'              # Run on the 1st of every month at 00:00 UTC
  workflow_dispatch:                # Allow manual trigger from the GitHub UI


permissions:
  contents: write

jobs:
  update-cleaned-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run cleaning script
        run: python scripts/clean_data.py

      - name: Commit cleaned data
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add data/cleaned_data.csv
          git commit -m "Auto-update cleaned data" || echo "No changes to commit"
          git push
