name: Monthly Data Refresh

on:
  push:
    paths:
      - 'data/raw_data.xlsx'
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-cleaned-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run cleaning script
        run: python scripts/clean_data.py

      - name: Commit cleaned data
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git pull origin main --rebase
          git add data/cleaned_data.csv
          git commit -m "Auto-update cleaned data" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main
